# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{verboten}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Olaf Delgado-Friedrichs", "ANUSF"]
  s.date = %q{2010-03-25}
  s.description = %q{
Verboten is a lightweight authorization plugin for Rails working on
the principle that everything is forbidden unless it is explicitly
permitted.

To enable the plugin for a given controller, include the command
'forbid_everything'. This defines two instance methods, 'permit' and
'before_authorization_filter'. The former is used to permit actions
selectively. The latter makes sure certain before filters run before
authorization is tested, so that they can set the required instance
variables (see examples in the README).
}
  s.email = %q{olaf.delgado-friedrichs@anu.edu.au}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/verboten.rb"
  ]
  s.homepage = %q{http://sf.anu.edu.au/~oxd900}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple white-list authorization for Rails.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/verboten_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

